### ISSUE TITLE
NameError name 'os' is not defined

### ISSUE THREAD

**Issue by williamchoukeir** [anjiro/bearutils#1]
I'm getting an error when I run bear.py.
![IMG_5915](https://user-images.githubusercontent.com/1987040/109470021-ce0dba80-7aa9-11eb-8155-4bb47faf5e94.PNG)

Thanks.

**Comment by anjiro** [comment]
Sorry for the late reply—I never got a notification about this issue. Try the latest version, it should fix the problem.
